# Logging data for HippoCampus

float32 x		# x-position in meters NED
float32 y		# y-position in meters NED
float32 z		# z-position in meters NED

float32 xd		# desired x-position in meters NED
float32 yd		# desired y-position in meters NED
float32 zd		# desired z-position in meters NED

float32[3] xa   # orientation x-axis in NED
float32[3] ya   # orientation y-axis in NED
float32[3] za   # orientation z-axis in NED

float32[3] xad  # desired orientation x-axis in NED
float32[3] yad  # desired orientation y-axis in NED
float32[3] zad  # desired orientation z-axis in NED

float32 t       # time